### ISSUE TITLE
Invalid argument: Maximum call stack size exceeded (bug in dart compiler)

### ISSUE THREAD

**Issue by TreyThomas93** [rrousselGit/riverpod#1713]
Edit: This is a dart web compiler bug, only for the debug web compiler, you can get around it by developing on desktop and testing / deploying a release build on web.
Upvote this issue: https://github.com/dart-lang/sdk/issues/50119

**Describe the bug**
Getting this error for Flutter web with Riverpod version 2.0:
```
 Invalid argument: Maximum call stack size exceeded
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   packages/riverpod/src/framework/auto_dispose.dart 7:24                                                            <computed>
│ #1   packages/riverpod/src/provider/base.dart 259:27                                                                   __
│ #2   packages/riverpod/src/provider/auto_dispose.dart 34:7     
```
Version 1.0.3 worked fine on web, but using version 2.0 seems to be giving me this error.
No issues found on Android/iOS. Just web so far.

**To Reproduce**
I am not really sure how to reproduce this for the provider file is quite lengthy. I am actively looking for the source but thought I should post this for the time being.

**Comment by TreyThomas93** [comment]
I have been able to pinpoint where the error is occurring. It appears that if I am watching a provider in more than one place within the same widget, and the provider is using .autoDispose, then it will result in the error. Removing .autoDispose fixes the issue. As I said, this is only happening on Flutter web.

After "fixing" that, I noticed the same issue was occurring when I called .listen on a provider, regardless if it had .autoDispose added to it.

_Calls This_
```
ref.listen(firstPhaseProvider, (_, bool isComplete) async {
            if (isComplete == true) {
              // Fire off second phase
              await Future.wait([
                ref
                    .read(sessionsSyncProvider.notifier)
                    .fetchSessionsFromServer(),
                // ref
                //     .read(weeklistsSyncProvider.notifier)
                //     .fetchWeeklistFromServer(),
                ref
                    .read(supervisorsSyncProvider.notifier)
                    .fetchSupervisorsFromServer(),
              ]);
            }
          });

final firstPhaseProvider = Provider.autoDispose<bool>((ref) {
  final servicesDone = ref.watch(servicesSyncProvider);
  final patientsDone = ref.watch(patientsSyncProvider);
  final referralsDone = ref.watch(pendingReferralsSyncProvider);

  if (servicesDone != const SyncStatus.syncing() &&
      patientsDone != const SyncStatus.syncing() &&
      referralsDone != const SyncStatus.syncing()) {
    return true;
  }

  return false;
}, name: "FirstPhaseProvider");
```

_Gets This_
```
 Invalid argument: Maximum call stack size exceeded
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   packages/riverpod/src/framework/auto_dispose.dart 7:24                                                           <computed>
│ #1   packages/riverpod/src/provider/base.dart 259:27                                                                  __
│ #2   packages/riverpod/src/provider/auto_dispose.dart 34:7    
```

**Comment by TreyThomas93** [comment]
It appears that if I am watching any provider with an .autoDispose that it is giving me this error. _Flutter Web_

**Comment by 7mada123** [comment]
I'm facing the same issue

**Comment by JulianSwales** [comment]
I am having the same issue. I have a sample app here with it failing. https://github.com/JulianSwales/test_web

**Comment by rich-j** [comment]
`2.0.0-dev.9` worked on the web, `2.0.1` fails as shown above. iOS is fine on both versions.

**Comment by deyjishnu** [comment]
> `2.0.0-dev.9` worked on the web, `2.0.1` fails as shown above. iOS is fine on both versions.

I confirm the same. Facing the issue on web with version `2.0.1`, but both `2.0.0` and `2.0.0-dev.9` works

**Comment by TimWhiting** [comment]
From git-bisect the breaking commit was this one:
f36e968f995d7ce9da2db61f0d580f7c5ffa9a63

**Comment by TimWhiting** [comment]
The dart web-simple template with the following works fine. So I'm guessing it's not related to the autoDispose mechanism in relation to the `ProviderContainer` but rather something to do with `ProviderScope` widgets in flutter.
```dart
import 'dart:html';
import 'package:riverpod/riverpod.dart';

void main() {
  final container = ProviderContainer();
  final value = container.read(stringValue.state);
  querySelector('#output')?.text = 'Your ${value.state} app is running.';
  final _ = container.listen(stringValue.state, (_, value) {
    querySelector('#output')?.text = 'Your ${value.state} app is running.';
  }, fireImmediately: true);
}

final stringValue = StateProvider.autoDispose((ref) => 'Hello world');

```

**Comment by schultek** [comment]
It is reproducible without flutter using the dart web-simple template and the following snippet:

```dart
import 'dart:html';
import 'package:riverpod/riverpod.dart';

void main() {
  final container = ProviderContainer();
  final value = container.read(stringValue.state);

  querySelector('#output')?.text = 'Your ${value.state} app is running.';

  final sub = container.listen(stringValue.state, (_, value) {
    querySelector('#output')?.text = 'Your ${value.state} app is running.';
  }, fireImmediately: true);

  container.read(stringValue.notifier).state = 'Hello changed';

  sub.close();
}

final stringValue = StateProvider.autoDispose((ref) => 'Hello world');
```

The error / stack trace is:
```
Uncaught RangeError: Maximum call stack size exceeded
    at set [_keepAliveLinks] (riverpod.sound.ddc.js:9149:38)
    ... (the same line many times)
    at set [_keepAliveLinks] (riverpod.sound.ddc.js:9149:38)
    at AutoDisposeProviderElementMixin.<computed> (riverpod.sound.ddc.js:2041:29)
    at StateProviderElement_AutoDisposeProviderElementMixin$36.__ (riverpod.sound.ddc.js:9137:68)
    at new AutoDisposeStateProviderElement.__ (riverpod.sound.ddc.js:9174:52)
    at AutoDisposeStateProvider.new.createElement (riverpod.sound.ddc.js:8995:16)
    at [_create] (riverpod.sound.ddc.js:4577:44)
    at framework._StateReader.new.getElement (riverpod.sound.ddc.js:4568:60)
    ...
```

So it seems like the js `_keepAliveLinks` setter is calling itself recursively.

**Comment by TimWhiting** [comment]
Thanks for that @schultek, I actually just realized that I was on the commit prior to the breaking commit when testing the webdev snippet. Was able to reproduce, with just the read on the container.

Filed https://github.com/dart-lang/sdk/issues/50119, since I believe it is a web compiler issue.

**Comment by TimWhiting** [comment]
While creating the dart issue, I found that I don't get this error for an AOT web build.

**Comment by schultek** [comment]
I found a non-riverpod snippet that reproduces the issue, which I added to the ticket. So this can possibly be closed.

**Comment by rrousselGit** [comment]
Thank you all for your investigation.

That pure Dart example posted in the related issue is quite a funky one.

**Comment by Patrick386** [comment]
Flutter Web:
Same error, version 1.0.3 worked fine on the web, but when I use version 2.0 I get this error.

**Comment by rrousselGit** [comment]
Well first it'd be nice to have a reply from the Dart team.

It's a bug. So it doesn't have to take months to be released. It could be cherry-picked.
If not, then I'll think of a solution. Although I'd like to avoid having to do a large refactor just because of a Dart bug

**Comment by TimWhiting** [comment]
In the meantime, everyone please add a thumbs up to the linked dart issue, to help them prioritize this for a fix and cherry pick.

**Comment by iLoveDocs** [comment]
Here's the minimal code (if anyone was looking for)

I get the error when I use `autoDispose` on either the `FutureProvider` or `StreamProvider` 

```dart
void main() => runApp(ProviderScope(child: MaterialApp(home: FooPage())));

class FooPage extends ConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    ref.watch(fooProvider);
    return Container();
  }
}

final fooProvider = FutureProvider.autoDispose<int>((ref) => Future.value(0));
```

**Comment by GregoryConrad** [comment]
For what it is worth, I only had this bug when in debug on web. Release mode seemed to be not affected.

**Comment by 1l0** [comment]
Seems to be related:
https://github.com/rrousselGit/riverpod/issues/1636
https://github.com/rrousselGit/riverpod/issues/1650

**Comment by TreyThomas93** [comment]
Can confirm that this is only an issue when running the app in DEBUG mode. When I run it in RELEASE mode, I do not get the error.

**Comment by ShoYakup** [comment]
Here's the minimal code (if anyone was looking for)

I get the error when I use autoDispose on either the FutureProvider or StreamProvider

```
void main() => runApp(ProviderScope(child: MaterialApp(home: FooPage())));

class FooPage extends ConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    ref.watch(fooProvider);
    return Container();
  }
}

final fooProvider = FutureProvider.autoDispose<int>((ref) => Future.value(0));
```

**Comment by MickyHuyHa** [comment]
I have a same issue.
I fixed it by upgrade environment version in pubspec.yaml
From:
```
environment:
  sdk: ">=2.14.0 <3.0.0"
```
To:
```
environment:
  sdk: ">=2.17.0 <3.0.0"
```

**Comment by radvansky-tomas** [comment]
That doesnt fix it, at least not on my machine. We run 2.17 for a long time and that issue is there since last upgrade

**Comment by MickyHuyHa** [comment]
I downgraded it, but the issue isn't still happened
I share my version info:
```
Flutter 3.3.2 • channel stable • https://github.com/flutter/flutter.git
Framework • xxxxxxxx
Engine • xxxxxxx
Tools • Dart 2.18.1 • DevTools 2.15.0
```
I found that may be I upgraded Flutter before change dart version and confuse it is rootcause
I think this can related Flutter version ??

Hope to help u

**Comment by leehack** [comment]
I added a PR for a fix. I think the fix can be used until the dart team officially fix the issue.
