### ISSUE TITLE
VS Code refactoring options are not available with Flutter 3.24 stable release

### ISSUE THREAD

**Issue by RepliedSage11** [rrousselGit/riverpod#3693]
**Describe the bug**
After upgrading Flutter to 3.24 stable the ability to do Riverpod refactors disappeared from the VS Code refactor dropdown.

Edit: I have found a similar [issue](https://github.com/rrousselGit/riverpod/issues/3582) from some time ago. Feel free to close if mine is a duplicate.

**To Reproduce**

Open the VS Code refactor menu (⌘ + . in my case) and see that no Riverpod-specific refactors are available.
**No converting widgets to ConsumerWidgets**
<img width="458" alt="image" src="https://github.com/user-attachments/assets/e60f156c-d202-4ae6-b789-1c552e094ab2">

**No converting function providers to class-based providers**
![image](https://github.com/user-attachments/assets/c95ee7d9-ba1a-4862-b5eb-b717201d2d77)

**Expected behavior**
The options should be available.

**Comment by rrousselGit** [comment]
Yes this is a known issue.

**Comment by Trung15010802** [comment]
When this will be fix. I can't live without it LOL

**Comment by rrousselGit** [comment]
Fixed

**Comment by ChaStPierre** [comment]
I've installed the latest version and I still have the issue. Thanks

**Comment by behnamsattar** [comment]
I'm still experiencing this issue.

Flutter 3.24.3
Riverpod_lint 2.3.13
Analyzer 6.7.0 (can't upgrade to the latest due to compatibility issues with the SDK)

**Comment by behnamsattar** [comment]
I'm still experiencing the issue.

flutter 3.24.3
riverpod_lint 2.3.13
analyzer 6.7.0
custom_lint 0.6.7
vscode 1.93.0

**Comment by AngDrew** [comment]
since i'm still having the same issue, i use this extension and it works like magic
https://marketplace.visualstudio.com/items?itemName=HoussemBousmaha.riverpod&ssr=false#overview

**Comment by Trung15010802** [comment]
> since i'm still having the same issue, i use this extension and it works like magic https://marketplace.visualstudio.com/items?itemName=HoussemBousmaha.riverpod&ssr=false#overview

What about StatefulWidget?

**Comment by AngDrew** [comment]
> > since i'm still having the same issue, i use this extension and it works like magic https://marketplace.visualstudio.com/items?itemName=HoussemBousmaha.riverpod&ssr=false#overview
> 
> What about StatefulWidget?

well, i don't use it often.. thanks to FlutterHook 🙏 
i'll stick with this solution for now.. because i can't use the refactor from `custom_lint` 🤷

**Comment by Trung15010802** [comment]
**I wrote an extension for vscode here:**

https://marketplace.visualstudio.com/items?itemName=QuangTrung.riverpod-widget-refactor

**Comment by behnamsattar** [comment]
> **I wrote an extension for vscode here:**
> 
> https://marketplace.visualstudio.com/items?itemName=QuangTrung.riverpod-widget-refactor

I am the second install 🎉 
Thanks @Trung15010802!

**Comment by MonkeyDrone** [comment]
I'm also  experiencing this issue.

flutter 3.24.3
riverpod_lint 2.3.13
analyzer 6.7.0
custom_lint 0.6.7
vscode 1.93.1

The extension from @Trung15010802  works though.

**Comment by quyenvsp** [comment]
This seem fixed by https://github.com/dart-lang/sdk/commit/a0411ae24485526470b7f99148132f29fe01edcb
Not sure when it release to stable Dart version, but I build custom dart sdk base on 3.5.4 then cherry-pick this commit and all seem smooth now, just info for someone want to try.

**Comment by Cunibon** [comment]
I started experiencing this again with flutter 3.35.3

**Comment by quyenvsp** [comment]
@Cunibon for me it never fixed yet.
but you can try apply my patch here to your local custom_lint package
https://github.com/invertase/dart_custom_lint/pull/340/commits/f270e4581dfa9ddb91bd867d7806e3b43229aa70
it work perfect for me but not merged yet.
