### ISSUE TITLE
Invalid argument(s): Cannot find import for AsyncValue

### ISSUE THREAD

**Issue by skeyboy** [rrousselGit/riverpod#4428]
**Describe the bug**

<img width="690" height="261" alt="Image" src="https://github.com/user-attachments/assets/05c5144b-d926-47c7-8ff8-bb88a7b08af8" />

<img width="640" height="283" alt="Image" src="https://github.com/user-attachments/assets/e95cff54-077a-473f-a3e2-b488fdef791e" />
Undefined name 'state'.
Try correcting the name to one that is defined, or defining the name.dart[undefined_identifier](https://dart.dev/diagnostics/undefined_identifier)
Type: InvalidType

riverpod_generator on lib/models/apple_login.dart:
  Invalid argument(s): Cannot find import for AsyncValue in _CanonicalizedUri(package:riverpod/riverpod.dart), and could not automatically import it.
  #0      AnalyzerBuffer._upsertImport (package:analyzer_buffer/src/analyzer_buffer.dart:544:5)
  #1      AnalyzerBuffer.write.<anonymous closure> (package:analyzer_buffer/src/analyzer_buffer.dart:701:28)
  #2      _parseCode (package:analyzer_buffer/src/analyzer_buffer.dart:750:12)
  #3      AnalyzerBuffer.write (package:analyzer_buffer/src/analyzer_buffer.dart:690:9)
  #4      RiverpodGenerator._generate (package:riverpod_generator/src/riverpod_generator.dart:86:14)
  #5      RiverpodGenerator.generateForUnit (package:riverpod_generator/src/riverpod_generator.dart:50:7)
  #6      ParserGenerator.generate (package:riverpod_generator/src/parse_generator.dart:38:12)
  <asynchronous suspension>
  #7      _generate (package:source_gen/src/builder.dart:370:23)
  <asynchronous suspension>
  #8      Stream.toList.<anonymous closure> (dart:async/stream.dart:1416:7)
  <asynchronous suspension>
  #9      _Builder._generateForLibrary (package:source_gen/src/builder.dart:116:9)
  <asynchronous suspension>
  #10     _Builder.build (package:source_gen/src/builder.dart:108:5)
  <asynchronous suspension>
  #11     runBuilder.buildForInput (package:build_runner/src/build/run_builder.dart:85:7)
  <asynchronous suspension>
  #12     Future.wait.<anonymous closure> (dart:async/future.dart:546:21)
  <asynchronous suspension>
  #13     BuildLogLogger.scopeLogAsync.<anonymous closure> (package:build_runner/src/logging/build_log_logger.dart:58:13)
  <asynchronous suspension>
  
**To Reproduce**

`

@riverpod
String helloWorld(Ref ref) {
  // await Future.delayed(Duration(seconds: 1), () {});
  return 'Hello world';
}

@riverpod
class Person extends _$Person {
  @override
  Future<String> build() async {
    return "None";
  }
}

`
**Expected behavior**

The riverpod is 3.0.3 , build action is dart run build_runner build --delete-conflicting-outputs

**Comment by rrousselGit** [comment]
You're using a version that has been pulled out of pub a few weeks ago. Run `flutter pub downgrade`. That should fix the issue.

**Comment by skeyboy** [comment]
That works. Thanks!!!

**Comment by swellee** [comment]
@rrousselGit hey bro, which version should I downgrade to? I tried v 3.0.2 but it still not working. thanks in advance!

**Comment by azhezzzz** [comment]
After updating `pubspec.yaml` and reinstalling the dependencies, it works.

```yml
dependency_overrides:
  # https://github.com/rrousselGit/riverpod/issues/4428#issuecomment-3562202572
  analyzer_buffer: 0.1.11
```

**Comment by gaojieusr** [comment]
That works. Thanks!!!

**Comment by xiegeo** [comment]
For anyone still stuck with this issue and want updated dependencies, removing custom_lint and freezed_lint from dev_dependencies did the trick for me.
